# name: Deploy to GitHub Pages

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#      uses: GY-CODING/.github/.github/workflows/next-deploy.yml@master
#      secrets: inherit
#      with:
#        domain: "accounts.gycoding.com"
